version: '3'

services:
    nginx:
      build: ./srcs/nginx/
      image: nginx
      container_name: nginx
      ports:
      - "443:443"
      networks:
        - net
      volumes:
       - vol:/var/www/html

    wordpress:
      build: ./srcs/wordpress/
      container_name: wordpress
      # command: tail -F anything
      ports:
      - "9000"
      networks:
        - net
      volumes:
       - vol:/var/www/html
    mariadb:
      build: ./srcs/mariadb/
      container_name: mariadb
      command: tail -F anything
      ports:
      - "3306"
      networks:
        - net
      volumes:
       - vol2:/var/lib/mysql
networks:
  net:
    driver: bridge
volumes:
  vol:
   driver: local
   driver_opts:
     o: "bind"
     type: "none"
     device: "/Users/yhebbat/Desktop/test"
  vol2:
   driver: local
   driver_opts:
     o: "bind"
     type: "none"
     device: "/Users/yhebbat/Desktop/test2"