FROM debian:buster
RUN apt-get update;\
    apt-get install -y nginx;\
	apt-get install -y openssl;\
    openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=Company, Inc./CN=mydomain.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt;
ADD ./conf/default /etc/nginx/sites-available/
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]